const countryList = {
    USD: "United States",
    GBP: "United Kingdom",
    JPY: "Japan",
    INR: "India",
    AUD: "Australia",
    CAD: "Canada",
    CNY: "China",
    CHF: "Switzerland",
    NZD: "New Zealand",
    ZAR: "South Africa",
    AED: "United Arab Emirates",
    SGD: "Singapore",
    SEK: "Sweden",
    NOK: "Norway",
    KRW: "South Korea",
    HKD: "Hong Kong",
    MXN: "Mexico",
    BRL: "Brazil",
    RUB: "Russia",
    SAR: "Saudi Arabia",
    TRY: "Turkey",
    THB: "Thailand",
    PKR: "Pakistan"
  };
  
